dist: trusty
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - travis_retry sudo apt-get update -q
 - travis_retry sudo apt-get install g++-4.9 cmake libasound2-dev -y
 - export CXX="g++-4.9" CC="gcc-4.9"
script:
 - mkdir build
 - cd build
 - cmake ..
 - make
 - sudo make install
